import { StatName, CategoryName } from './types';

export const STAT_NAMES: StatName[] = [
  'layup',
  'dunking',
  'paint',
  'dribbleSpeed',
  'dribbleControl',
  'passAccuracy',
  'agility',
  'speed',
  'strength',
  'vertical',
  'threePoint',
  'midRange',
  'freeThrow',
  'steal',
  'block',
  'offensiveRebound',
  'defensiveRebound',
];

export const STAT_DISPLAY_NAMES: Record<StatName, string> = {
  layup: 'Layup',
  dunking: 'Dunking',
  paint: 'Paint',
  dribbleSpeed: 'Dribble Speed',
  dribbleControl: 'Dribble Control',
  passAccuracy: 'Pass Accuracy',
  agility: 'Agility',
  speed: 'Speed',
  strength: 'Strength',
  vertical: 'Vertical',
  threePoint: 'Three Point',
  midRange: 'Mid Range',
  freeThrow: 'Free Throw',
  steal: 'Steal',
  block: 'Block',
  offensiveRebound: 'Offensive Rebound',
  defensiveRebound: 'Defensive Rebound',
};

export const CATEGORY_STATS: Record<CategoryName, StatName[]> = {
  finishing: ['layup', 'dunking', 'paint'],
  creativity: ['dribbleSpeed', 'dribbleControl', 'passAccuracy'],
  physicals: ['agility', 'speed', 'strength', 'vertical'],
  shooting: ['threePoint', 'midRange', 'freeThrow'],
  defense: ['steal', 'block'],
  rebound: ['offensiveRebound', 'defensiveRebound'],
};

export const DEFAULT_CAPS = {
  shooter: {
    layup: 7,
    dunking: 5,
    paint: 4,
    dribbleSpeed: 5,
    dribbleControl: 5,
    passAccuracy: 7,
    agility: 6,
    speed: 6,
    strength: 4,
    vertical: 6,
    threePoint: 9,
    midRange: 10,
    freeThrow: 9,
    steal: 4,
    block: 3,
    offensiveRebound: 3,
    defensiveRebound: 3,
  },
  finisher: {
    layup: 10,
    dunking: 9,
    paint: 8,
    dribbleSpeed: 7,
    dribbleControl: 7,
    passAccuracy: 6,
    agility: 7,
    speed: 7,
    strength: 8,
    vertical: 9,
    threePoint: 3,
    midRange: 5,
    freeThrow: 6,
    steal: 5,
    block: 6,
    offensiveRebound: 7,
    defensiveRebound: 5,
  },
  '3&D': {
    layup: 6,
    dunking: 4,
    paint: 5,
    dribbleSpeed: 6,
    dribbleControl: 5,
    passAccuracy: 6,
    agility: 7,
    speed: 8,
    strength: 6,
    vertical: 6,
    threePoint: 9,
    midRange: 7,
    freeThrow: 8,
    steal: 8,
    block: 7,
    offensiveRebound: 5,
    defensiveRebound: 8,
  },
  defender: {
    layup: 5,
    dunking: 5,
    paint: 6,
    dribbleSpeed: 6,
    dribbleControl: 5,
    passAccuracy: 7,
    agility: 8,
    speed: 8,
    strength: 7,
    vertical: 7,
    threePoint: 4,
    midRange: 5,
    freeThrow: 6,
    steal: 10,
    block: 9,
    offensiveRebound: 6,
    defensiveRebound: 9,
  },
};
